"""initial schema

Revision ID: 9aff7eeed93d
Revises: 
Create Date: 2026-05-23 15:03:28.968700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9aff7eeed93d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allocation_sessions',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('total_requirements', sa.Integer(), nullable=False),
    sa.Column('total_allocated', sa.Integer(), nullable=False),
    sa.Column('total_deficit', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('materials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sys_nomer', sa.String(length=50), nullable=False),
    sa.Column('naimenovanie', sa.Text(), nullable=True),
    sa.Column('ed_izm', sa.String(length=20), nullable=True),
    sa.Column('gruppa', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sys_nomer')
    )
    op.create_table('warehouses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kod_sklada', sa.String(length=50), nullable=False),
    sa.Column('tip_sklada', sa.String(length=50), nullable=True),
    sa.Column('filial', sa.String(length=100), nullable=True),
    sa.Column('zavod', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kod_sklada')
    )
    op.create_table('works',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kod_raboty', sa.String(length=100), nullable=False),
    sa.Column('tip_raboty', sa.String(length=100), nullable=True),
    sa.Column('is_emergency', sa.Boolean(), nullable=False),
    sa.Column('filial', sa.String(length=100), nullable=True),
    sa.Column('podrazdelenie', sa.String(length=100), nullable=True),
    sa.Column('centr_zatrat', sa.String(length=50), nullable=True),
    sa.Column('zavod', sa.String(length=50), nullable=True),
    sa.Column('data_nachala', sa.Date(), nullable=True),
    sa.Column('data_okonchaniya', sa.Date(), nullable=True),
    sa.Column('prioritet', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kod_raboty')
    )
    op.create_table('issued_not_written_off',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('work_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('kolichestvo', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('stoimost_za_ed', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('summa', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('data_vydachi', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_issued_work_material', 'issued_not_written_off', ['work_id', 'material_id'], unique=False)
    op.create_table('requirements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('work_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('potrebnost', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('prognosnaya_tsena', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('raspredeleno', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('deficit', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_requirements_work_material', 'requirements', ['work_id', 'material_id'], unique=True)
    op.create_table('stock_batches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('nomer_partii', sa.String(length=100), nullable=True),
    sa.Column('kolichestvo', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('dostupno', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('stoimost_za_ed', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('data_postupleniya', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_stock_batches_fifo', 'stock_batches', ['material_id', 'data_postupleniya'], unique=False)
    op.create_index('ix_stock_batches_material', 'stock_batches', ['material_id'], unique=False)
    op.create_table('supplies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dogovor', sa.String(length=100), nullable=True),
    sa.Column('postavshchik', sa.String(length=200), nullable=True),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('filial', sa.String(length=100), nullable=True),
    sa.Column('zavod', sa.String(length=50), nullable=True),
    sa.Column('data_postavki', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('writeoffs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('work_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('kolichestvo', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('stoimost_za_ed', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('summa', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('nomer_dokumenta', sa.String(length=100), nullable=True),
    sa.Column('data_spisaniya', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_writeoffs_work_material', 'writeoffs', ['work_id', 'material_id'], unique=False)
    op.create_table('deficit_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=True),
    sa.Column('work_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('deficit_qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('needed_by', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['allocation_sessions.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_deficit_material', 'deficit_records', ['material_id'], unique=False)
    op.create_index('ix_deficit_session', 'deficit_records', ['session_id'], unique=False)
    op.create_table('stock_movements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('work_id', sa.Integer(), nullable=True),
    sa.Column('izmenenie', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('ostatok', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('data_dvizheniya', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['stock_batches.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['allocation_sessions.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_movements_session', 'stock_movements', ['session_id'], unique=False)
    op.create_index('ix_movements_warehouse_material', 'stock_movements', ['warehouse_id', 'material_id'], unique=False)
    op.create_table('supply_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('supply_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('kolichestvo', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('dostupno', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('stoimost_za_ed', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['supply_id'], ['supplies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_supply_lines_material', 'supply_lines', ['material_id'], unique=False)
    op.create_table('allocation_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=True),
    sa.Column('work_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('istochnik', sa.String(length=50), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('supply_line_id', sa.Integer(), nullable=True),
    sa.Column('kolichestvo', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('srednyaya_stoimost', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('summa', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('tip_raspredeleniya', sa.String(length=50), nullable=True),
    sa.Column('is_possible', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['allocation_sessions.id'], ),
    sa.ForeignKeyConstraint(['supply_line_id'], ['supply_lines.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alloc_results_material', 'allocation_results', ['material_id'], unique=False)
    op.create_index('ix_alloc_results_session', 'allocation_results', ['session_id'], unique=False)
    op.create_index('ix_alloc_results_work', 'allocation_results', ['work_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_alloc_results_work', table_name='allocation_results')
    op.drop_index('ix_alloc_results_session', table_name='allocation_results')
    op.drop_index('ix_alloc_results_material', table_name='allocation_results')
    op.drop_table('allocation_results')
    op.drop_index('ix_supply_lines_material', table_name='supply_lines')
    op.drop_table('supply_lines')
    op.drop_index('ix_movements_warehouse_material', table_name='stock_movements')
    op.drop_index('ix_movements_session', table_name='stock_movements')
    op.drop_table('stock_movements')
    op.drop_index('ix_deficit_session', table_name='deficit_records')
    op.drop_index('ix_deficit_material', table_name='deficit_records')
    op.drop_table('deficit_records')
    op.drop_index('ix_writeoffs_work_material', table_name='writeoffs')
    op.drop_table('writeoffs')
    op.drop_table('supplies')
    op.drop_index('ix_stock_batches_material', table_name='stock_batches')
    op.drop_index('ix_stock_batches_fifo', table_name='stock_batches')
    op.drop_table('stock_batches')
    op.drop_index('ix_requirements_work_material', table_name='requirements')
    op.drop_table('requirements')
    op.drop_index('ix_issued_work_material', table_name='issued_not_written_off')
    op.drop_table('issued_not_written_off')
    op.drop_table('works')
    op.drop_table('warehouses')
    op.drop_table('materials')
    op.drop_table('allocation_sessions')
    # ### end Alembic commands ###
