"""remove centr_zatrat from works

Revision ID: a9a17b97ba8f
Revises: b5c2d9f30e58
Create Date: 2026-05-29 16:53:45.547685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9a17b97ba8f'
down_revision: Union[str, Sequence[str], None] = 'b5c2d9f30e58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('works', 'centr_zatrat')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('works', sa.Column('centr_zatrat', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
